#!/bin/bash

#
# Copyright (c) 2021, Mangdang Technology Co., Limited
#

#Power monitor
while true
do
	current_voltage=`cat /sys/class/power_supply/max1720x_battery/voltage_now`
	if [ $current_voltage -le 6500 ]; then
		echo 0 > /sys/class/gpio/gpio25/value
		echo 0 > /sys/class/gpio/gpio21/value
		# install scrip will replace BASEDIR
		mpg123 BASEDIR/audio/low_power.mp3
	fi
	sleep 8
done
